name: Integration Test
on: [push]
jobs:
  build_multiple_files_with_options:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Self test
        id: selftest
        uses: battlech1cken/typst-action@main
        with:
          source_file: |
            tests/valid.typ
            tests/math.typ
          base_options: |
            -vv
          compile_options: |
            --font-path
            fonts/
      - name: Check existence of output file
        run: |
          test -e "tests/valid.pdf"
          test -e "tests/math.pdf"
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Output PDF files
          path: tests/*.pdf
